export const mon = [
  { time: "8:00 AM", status: true },
  { time: "8:30 AM", status: true },
  { time: "9:00 AM", status: true },
  { time: "9:30 AM", status: true },
  { time: "10:00 AM", status: true },
  { time: "10:30 AM", status: true },
  { time: "11:00 AM", status: true },
  { time: "11:30 AM", status: true },
  { time: "12:00 PM", status: true },
  { time: "12:30 PM", status: false },
  { time: "01:00 PM", status: false },
  { time: "01:30 PM", status: true },
  { time: "2:00 PM", status: true },
  { time: "2:30 PM", status: true },
  { time: "3:00 PM", status: true },
  { time: "3:30 PM", status: true },
  { time: "4:00 PM", status: true },
  { time: "4:30 PM", status: true },
  { time: "5:00 PM", status: true },
];

export const wed = [
  { time: "8:00 AM", status: true },
  { time: "8:30 AM", status: true },
  { time: "9:00 AM", status: true },
  { time: "9:30 AM", status: true },
  { time: "10:00 AM", status: true },
  { time: "10:30 AM", status: true },
  { time: "11:00 AM", status: true },
  { time: "11:30 AM", status: true },
  { time: "12:00 PM", status: true },
  { time: "12:30 PM", status: false },
  { time: "01:00 PM", status: false },
  { time: "01:30 PM", status: true },
  { time: "2:00 PM", status: true },
  { time: "2:30 PM", status: true },
  { time: "3:00 PM", status: true },
  { time: "3:30 PM", status: false },
  { time: "4:00 PM", status: false },
  { time: "4:30 PM", status: false },
  { time: "5:00 PM", status: true },
];

export const sat = [
  { time: "8:00 AM", status: true },
  { time: "8:30 AM", status: true },
  { time: "9:00 AM", status: true },
  { time: "9:30 AM", status: true },
  { time: "10:00 AM", status: true },
  { time: "10:30 AM", status: true },
  { time: "11:00 AM", status: true },
  { time: "11:30 AM", status: true },
  { time: "12:00 PM", status: true },
];
